### ISSUE TITLE
Cmd+S not saving

### ISSUE THREAD

**Issue by drcahixson** [jgraph/drawio-desktop#1024]
System/Software Specs:

M1 MacBook Pro 
macOS 12.3 Beta
draw.io desktop using diagrams.net 18.1.3

Issue:

If I use Cmd+S to save OR if I use the File->Save dropdown menu to save, the changes will not be saved in the diagram upon reopening.

If I wait for the orange "Unsaved changes. Click here to save." popup to show up and click that, it will save just fine.

Thanks.

**Comment by mararad** [comment]
Hi,

When you click Cmd+S to save or File->Save, do you see "All changes saved" in the menu bar?

**Comment by drcahixson** [comment]
I don't remember what it was doing yesterday, but today I can confirm that it says "All changes saved" but does NOT save the changes.

**Comment by hesperanca** [comment]
I'm having a similar issue with text labels. If I open a diagram, change a text label, click Ctrl+S, and close the diagram my changes do not get saved and no warning is given. In order to save them I have to click out of the shape which will then trigger the autosave. I've lost quite a few changes with this.

My environment:
draw.io desktop 
windows 11 
diagrams.net 19.0.3

**Comment by davidjgraph** [comment]
@hesperanca that's not the same issue, that how text labels are intended to work. If you disagree, please start a new thread.
