### ISSUE TITLE
Opening and saving a diagram exported as png discards export settings

### ISSUE THREAD

**Issue by Griffon26** [jgraph/drawio-desktop#1099]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Opening and saving a diagram exported as png may modify the diagram (it loses non-default export options such as border width and background).

**To Reproduce**
1. Create a new non-empty diagram (for example the default class diagram)
3. Click on File -> Export as PNG...
4. Set border width to 10
5. Set "Include a copy of my diagram"
6. Save it as a .png file
7. Open the png file in an image viewer to confirm that it has a border
8. Open the png file with draw.io-desktop again
9. Click File -> Save
10. Open the png file in an image viewer to confirm that it has no border

**Expected behavior**
Opening a png exported with certain options and saving it should not result in a different image

**Screenshots**
![diagram_after_first_export](https://user-images.githubusercontent.com/7215199/186921511-1c68970f-2719-4feb-af11-b06558ef2b76.png)
![diagram_after_consequent_save](https://user-images.githubusercontent.com/7215199/186921603-9aceffbe-f104-4e17-9327-d060573652dc.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.2.3

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by amamabel** [comment]
Same here (v21.2.8). Save PNG with integrated diagram, open saved PNG with drawio, modify something and save it with ctrl-s leave the new PNG with many errors.

Workaround is to not save it via ctrl-s instead to use the export to PNG again.

**Comment by kevinrobbins** [comment]
I also ran into this issue, but I don't think this is a bug. I think the issue is that when exporting the diagram to PNG, the export settings are applied only to the image, but not the actual diagram. The diagram is embedded as-is and when you save the file again, the original diagram is saved. Unless you've configured the diagram settings to match what you select on PNG export, it will look wrong.

In my case, I exported without a transparent background and with a 10px border. After opening and saving again, the PNG had a transparent background and no border. To solve, I did the following:

1. Set a background color for the diagram (e.g. white). By default the background is transparent. Apparently PNG export defaults to white. This option is found in the Diagram properties panel.
2. Set the diagram border to 10px. This option was found under File -> Properties.

After making these changes, saving the PNG diagram resulted in the expected format.
