### ISSUE TITLE
How can I use cli parameters with "windows no installer exe"

### ISSUE THREAD

**Issue by korpa** [jgraph/drawio-desktop#113]
If I run the "windows no installer exe" with cli parameters, it just returns with an empty line instead of a help message:
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

D:\>draw.io-10.7.5-windows-no-installer.exe -h

D:\>
```
Release notes for version 10.7.5 assume, that I can use cli parameters like this:
https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by davidjgraph** [comment]
-h, --height fits the generated image/pdf into the specified height, preserves aspect ratio.
--crop crops PDF to diagram size

You've specified no input file, add -x and the path.

**Comment by korpa** [comment]
Ok. There seems to be an issue in the release notes:
![image](https://user-images.githubusercontent.com/2982785/59914879-a54fa980-941b-11e9-9d7f-5df70956f9e8.png)

I tried to get the help with `-h`

Now I tried `--help` to get the help. Same issue:
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

D:\>draw.io-10.7.5-windows-no-installer.exe --help

D:\>
```

**Comment by davidjgraph** [comment]
Fixed, thanks for the report.

**Comment by korpa** [comment]
Sorry to bother you again. I'm not sure if cli parameters work with the "no installer exe". I tried the `version` parameter now:

```
D:\drawio>draw.io-10.7.5-windows-no-installer.exe --version

D:\drawio>draw.io-10.7.5-windows-no-installer.exe --V

D:\drawio>
```

Even if I try to render a drawing into a pdf, it doesn't work:

```
D:\drawio>draw.io-10.7.5-windows-no-installer.exe -x architecture.drawio

D:\drawio>
```
I would expect that a file called `architecture.pdf` in the same directory will be created or at least an error message is shown.

**Comment by korpa** [comment]
@davidjgraph Do you had already time to double check the behavior I described in my last comment?

**Comment by davidjgraph** [comment]
No, I won't have time to look, but I'll reopen so someone else can.

**Comment by ashrafteleb** [comment]
I've tried the portable version (no-install) and it works in terms of exporting draw.io diagrams. But, it doesn't show any message in the command prompt. This is an issue with Electron-builder and we will report it to them.

Meanwhile, you can use draw.io CLI with the portable version but you need to make sure all arguments are correct since all error/info messages are not shown

**Comment by ashrafteleb** [comment]
Electron-builder issue:
electron-userland/electron-builder#3998

**Comment by BeKl92** [comment]
Is there already a solution / workaround to use cli parameters with portable version?

**Comment by m-mohamedin** [comment]
As stated above, it works but with no output. It is an issue with electron builder and it's not fixed yet

**Comment by ImGajeed76** [comment]
Hey,

I attempted to use the CLI to export my files to PDF. Initially, I was confused because the `--help` command did not produce any output. Despite this, I proceeded to run the export command, but it did not work as expected.

Specifically, it appears that the CLI does not function correctly with the “windows-no-installer” option. My command might be incorrect, but without any error messages or output, it’s difficult to diagnose the problem.

I noticed that this Problem was moved to done, but it doesn't seem to be fixed… Furthermore, will the CLI ever get its official Documentation (Or am I just too stupid to find it on the website)?

**Comment by rstephan** [comment]
I have placed the `--help` output here for future reference:

https://gist.github.com/rstephan/f273689a491a2d8d69b9c1944f8ad961

All filenames must contain absolute path names. The "no-installer" is silently extracted somewhere into a temporary folder and executed from there. All arguments are passed to it without modifications, so relative files don't work as expected.

**Comment by ImGajeed76** [comment]
Thanks for the answer, but i would have needed that 11 months ago 😂
