### ISSUE TITLE
Cannot print in landscape orientation with any printer

### ISSUE THREAD

**Issue by flusheDData** [jgraph/drawio-desktop#1164]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Cannot print in landscape orientation with any of my printers (including OS' Print to PDF)

**To Reproduce**
1. Go to 'File>Page setup'
2. Click on 'Landscape'
3. Go to 'File>Print' (confirmed it is in landscape orientation)
4. Click on 'OK'
5. Select any printer
6. Click on 'Print'

**Expected behavior**
A Landscape oriented printout

**Screenshots**

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.3.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by flusheDData** [comment]
I found out that, despite having chosen the Landscape orientation wether in **File > Page setup** or **Print** menus the system printer's dialog still shows **Portrait** orientation.
Having found this out it is ok for me to have this thread closed. It would be great to make Draw.io Desktop able to change the system printer's orientation too tho.
Best regards

**Comment by Air16** [comment]
+ 1

**Comment by dunxd** [comment]
It isn't just orientation that isn't passed to the printer.  The page size also isn't.  If a drawing is set with an A3 page size, the printer isn't told about it.  I don't think any of these settings are passed to the OS printing process when clicking OK:

![image](https://github.com/jgraph/drawio-desktop/assets/16608541/eff63c85-14b6-4383-9e08-1c8b7e4df9d4)

In my opinion it would be better not to show this dialog which suggests to the user that changes will be applied to their print job when they aren't.  Just go straight to the OS printer dialog where adjustments can be made.  Don't tell the user that something is being done when it isn't and then expect them to remember they have to make all those settings again.

This issue is the same for all printers, including print to PDF, on both Windows and Mac.

**Comment by davidjgraph** [comment]
Duplicate #517
