### ISSUE TITLE
Importing svg's into Library bug

### ISSUE THREAD

**Issue by benbaker76** [jgraph/drawio-desktop#1186]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When importing [Python-logo-notext.svg](https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg) into a Library part of it is cut off. Also trying to import [Elasticsearch_logo.svg](https://upload.wikimedia.org/wikipedia/commons/f/f4/Elasticsearch_logo.svg) I get an error "Unknown error" `Uncaught TypeError: Cannot read properties of undefined (reading '0')`.

**To Reproduce**
1. Go to 'File->New LIbrary.'
2. Drag the two svg's into the window

**Expected behavior**
For the svg not to be cut off and for there to be no error.

**Screenshots**
![Screenshot from 2022-12-09 12-51-07](https://user-images.githubusercontent.com/1698401/206763053-1d84c6e2-0404-4d97-9922-39ebc0e0d982.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- diagrams.net 20.6.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS

**Additional context**

**Comment by davidjgraph** [comment]
There was no desktop release 20.6.1. Which version was tested?

**Comment by benbaker76** [comment]
> There was no desktop release 20.6.1. Which version was tested?

It's the version I get in the About window.
![Diagrams-net-20-6-1](https://user-images.githubusercontent.com/1698401/211712384-12665aa9-e745-4a75-86ea-2e03b28f6e5c.png)

**Comment by davidjgraph** [comment]
OK, not sure how that happened. I'd suggest updateing to the latest release

**Comment by benbaker76** [comment]
> OK, not sure how that happened. I'd suggest updateing to the latest release

I just tried the latest version (20.7.4) and get the same issue

**Comment by SudoCerb** [comment]
I was literally searching for this exact issue, with (possibly the exact) same SVG file.

Let me see if I can add more information.

For some reason, all the SVG files provided by python.org, and wikimedia.org for a Python logo are not being imported correctly.

I downloaded a Rust logo from wikimedia.org and that worked fine.

Finally I found a Python logo at worldvectorlogo.com which works!

I'm guessing that the SVGs generated for python.org were somehow made with incorrect parameters.


![image](https://user-images.githubusercontent.com/19804004/225599642-1d302359-cbab-47d0-adab-05d82a324dc7.png)

Here are the links to the SVG files that I have tried:

**python.org**
 - https://www.python.org/static/community_logos/python-logo-generic.svg
 - https://www.python.org/static/community_logos/python-logo-inkscape.svg
 - https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg <sup>1</sup>

**wikimedia.org**
 - https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg
 - https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg <sup>1</sup>

**worldvectorlogo.com**
 - https://worldvectorlogo.com/logo/python-5

Version information:
`diagrams.net 20.8.10`

Desktop (please complete the following information):

OS: Windows 11 Enterprise

I'm happily going to use the SVG that worked correctly, but I hope that the above info can help!

Footnotes:
1. I checked the SHA256 hash of these two because they were so similar in size, but they are two different files.
