### ISSUE TITLE
New update v20.6.1 breaks application on theme change

### ISSUE THREAD

**Issue by deepu2** [jgraph/drawio-desktop#1188]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
I updated the application to 20.6.1 when it prompted. After updating I changed the interface theme to Sketch from Extras > Theme. It showed a dialog changes will be applied after restarting the application. I also had autosave turned on.

**To Reproduce**
1. Enable Autosave
1. Go to Extras
2. Click on Theme
3. Select Sketch
4. Close the application and restart
5. See blank white screen

**Expected behavior**
After restarting the application did not start correctly, it is showing white screen indefinitely.

**Screenshots**
![draw io_yptpaW2CvR](https://user-images.githubusercontent.com/30926681/206826909-5eb6ac8a-e669-4242-a539-2a592305dadb.png)
![draw io_ZSG4ltDtsr](https://user-images.githubusercontent.com/30926681/206826911-bbc712b9-7ac5-4628-afbe-ea1366fb4ca3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.6.1

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I used the Windows Installer version.
I tried uninstalling and reinstalling to default directory, reinstalling to other directory but everything resulted in the same white screen.
For now downgrading to 20.3.0 seems to be working.

**Comment by Silent-Baikal** [comment]
thank you very much。



---Original---
From: "Deepak ***@***.***&gt;
Date: Sat, Dec 10, 2022 11:32 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jgraph/drawio-desktop] New update v20.6.1 breaks application ontheme change (Issue #1188)




 
Preflight Checklist
  
 I agree to follow the Code of Conduct that this project adheres to.
 
 I have searched the issue tracker for a feature request that matches the one I want to file, without success.
  
You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.
 
Describe the bug
 I updated the application to 20.6.1 when it prompted. After updating I changed the interface theme to Sketch from Extras &gt; Theme. It showed a dialog changes will be applied after restarting the application.
 
To Reproduce
 Steps to reproduce the behavior:
  
Go to Extras
 
Click on Theme
 
Select Sketch
 
Close the application and restart
 
See blank white screen
  
Expected behavior
 After restarting the application did not start correctly, it is showing white screen indefinitely.
 
Screenshots
 
 
 
draw.io version (In the Help-&gt;About menu of the draw.io editor):
  
draw.io version 20.6.1
  
Desktop (please complete the following information):
  
OS: Windows
  
Additional context
 I used the Windows Installer version.
 I tried uninstalling and reinstalling to default directory, reinstalling to other directory but everything resulted in the same white screen.
 For now downgrading to 20.3.0 seems to be working. The older version had the Sketch theme applied.

**Comment by davidjgraph** [comment]
Thanks for the report, please try 20.6.2.

**Comment by deepu2** [comment]
This fixed it, thanks!

**Comment by Lake-Baikal** [comment]
thank you very much



---Original---
From: "Deepak ***@***.***&gt;
Date: Tue, Dec 13, 2022 11:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jgraph/drawio-desktop] New update v20.6.1 breaks application ontheme change (Issue #1188)




 
This fixed it, thanks!
