### ISSUE TITLE
error on line 1 at column 1048577: Extra content at the end of the document

### ISSUE THREAD

**Issue by DavidenMaaike** [jgraph/drawio-desktop#1218]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
Cannot open the draw.io file anymore.

**To Reproduce**

Open file.

**Expected behavior**
A clear and concise description of what you expected to happen:
The files open normally with all its content.

**Screenshots**
If applicable, add screenshots to help explain your problem:

![image](https://user-images.githubusercontent.com/123895406/215346480-a92192d4-8d08-441a-aa60-d887146165a3.png)

**draw.io version (In the Help->About menu of the draw.io editor):**
diagrams.net 20.8.10

- draw.io version x.y.z
20.8.10

**Desktop (please complete the following information):**
Windows 10

**Additional content:**
error on line 1 at column 1048577: Extra content at the end of the document
[Plan tekening Tembo 4x4.zip](https://github.com/jgraph/drawio-desktop/files/10530499/Plan.tekening.Tembo.4x4.zip)

Thank you in advance for fixing my file! I worked on this for months.

**Comment by davidjgraph** [comment]
This was auto-saving to your local filesystem? Was the folder synchronised to another service, like OneDrive, for example?

**Comment by DavidenMaaike** [comment]
The file was auto-saving to my local filesystem when the problem occurred.

**Comment by HenrikM1** [comment]
I have exactly the same problem. I am also using version 20.8.10.
I'm running Windows 11, and my files are on Google Drive.

Just before saving I had added a connector that behaved strangely:
It was colored red when I created it. I deselected it, and then it could not be selected again.
When I tried to save the file, it got corrupted.

This is a pretty serious problem. Is there a fix in sight?

**Comment by HenrikM1** [comment]
I opened the file in notepad and saw that it has extra tags at the end. I have attached a screenshot.

Found another report about the same, or a very similar, problem, from 2021: https://github.com/jgraph/drawio-desktop/issues/478

<img width="605" alt="image" src="https://user-images.githubusercontent.com/90210437/221926131-091fe4dc-5d26-4a25-ba14-c64daa536627.png">

**Comment by HenrikM1** [comment]
I got the same error again. This time, the file ended like this:

\</diagram></mxfile>/mxfile>

Because the last tag has a missing <, I would guess that you are writing the file using some kind of home grown stream parser. The nested mxfile tags suggest that you do not validate against a schema before saving the file.

Switching to the XML DOM might be too much work, but validating the XML before saving it, should be an easier fix. Validation, of course, just protects against overwriting files, it does not catch the actual bug.

Looks to me like iodraw is trying to merge two XML documents, and confuses a document root element with the content of that element. Why iodraw would want to merge two documents in the first place, I do not know. There is only one document.

However, iodraw opens a dialog and asks if it should merge documents before saving. It should not do that, since there is only one document. It should just save when told to save. I think the merge behavior may have something to do with the problem.

**Comment by alderg** [comment]
Is this in a synced folder?

**Comment by HenrikM1** [comment]
> Is this in a synced folder?

Yes. I am using Google Drive. However, this bug has been reported before, as far back as January 2021, at least. I am probably the only one who has reported the bug that uses synced folders.

Wild guess, but it looks to me more like draw.io has problems with files that contain multiple diagrams, than it looks like a program with the file system.

I got the same error again just a few minutes ago. Looks like there is more and more junk characters each time it happens.

At this point, I am spending more time editing the XML file in notepad than editing diagrams in draw.io.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/90210437/222362406-33026517-3750-4709-816e-4a42ac953b3d.png">

**Comment by alderg** [comment]
We're unable to reproduce this. Could you do a test for us to help us narrow down this problem. If you create a file with a rectangle and save that, remove the rectangle (so that the file gets smaller) and save that again, do you get this error? (If yes, do get this on both, local and synced folders?)

**Comment by HenrikM1** [comment]
I was unable to replicate the problem with a small file.

However, every time I save to the G: drive draw.io opens a dialog and says there have been external changes. When I save to a local drive, this does not happen.

You have probably noticed already that the extra characters  aren't random. They replicate the end of the end of the XML document.

Today, the problem has occurred even when I haven't changed anything in the document. Saving several times in a row is enough for the problem to occur.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/90210437/222413375-6d561b2f-aad5-4088-b84a-69b5accfa20b.png">

**Comment by HenrikM1** [comment]
One more bit of information:

When draw.io messes up a file, it saves the file, with duplicated characters, and then immediately opens a dialog that says "All saving trials failed."

So, it knows it has messed up _after_ it has saved, but _before_ I have tried to open the file again.

I don't know if this helps.

I'm getting very frequent errors today. Possibly because I have a large file with several fairly complicated diagrams.

**Comment by HenrikM1** [comment]
I turned off file compression in draw.io yesterday evening. I have been able to work for 5 hours without any problems saving.

Might be coincidence, but then again, it might be a clue to where saving goes wrong.

**Comment by m-mohamedin** [comment]
Hi @HenrikM1,

Unfortunately, I couldn't reproduce the error. If possible, can you share with us the diagram on mohamedin@draw.io

Some information to help understanding the different messages.
- Merge message appear when another editor/process changes the file. So, Google Drive for some reason is changing the file while you work on it.
- "All saving trials failed" error means we couldn't save the file correctly. We read the saved data after writing it to the desk to confirm it is written correctly (due to other reports of corrupted files). If the read data doesn't match, we try again until all trials fail.

So, can you check if the file is not shared with others. Also, any special Google Drive settings that can cause this conflicting writes to the file?

Thanks

**Comment by HenrikM1** [comment]
> Hi @HenrikM1,
> 
> Unfortunately, I couldn't reproduce the error. If possible, can you share with us the diagram on [mohamedin@draw.io](mailto:mohamedin@draw.io)

Hi,
Unfortunately I cannot share the file. It contains proprietary information.
The file is not shared with others. It is stored locally.

I switched to saving the diagram uncompressed, and since then, I have had no problems with extraneous characters. 

The merge dialog still pops up though. My guess is that it pops up because Google Drive has uploaded a new version to the cloud.

**Comment by davidjgraph** [comment]
OK, given that the only solution found so far is switching off compression we are assuming there is a bug in the JS compression library somewhere. We'll switch off compression by default in the next release.

**Comment by VictorD92** [comment]
Hello!
I had the same error, so I added `</diagram></mxfile>` to the end of the file.
Unfortunately I still have an error. Now it is just saying "not a diagrma file". Anyone knows how to fix this?
I had saved the png file before that, so maybe there is a way to retrieve the drawio xml file from the png (tried some solutions on the internet, did not find a way to do it nicely). It is in the zip

[chartes_avec_et_sans_rep.zip](https://github.com/jgraph/drawio-desktop/files/11610871/chartes_avec_et_sans_rep.zip)

**Comment by frenchbrian** [comment]
I was having the same issue. This appears to happen when storing in a synced folder (using Zoho Workdrive in this case, but notice the original poster was using Google Drive). Saving to a non-synced folder fixed the issue.

**Comment by davidjgraph** [comment]
Moving issue to https://github.com/jgraph/drawio-desktop/issues/1366
