### ISSUE TITLE
Feature to import of Stencils and Shapes from Visio (or other non-native mediums), like the online edition.

### ISSUE THREAD

**Issue by jdmac87** [jgraph/drawio-desktop#1316]
* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**
I like to work on Draw.io using the desktop edition, but one limitation that is frustrating is not being able to import Visio Stencils and Shapes from my vendors.

**Describe the solution you'd like**
I would like to request the feature of being able to import from other media be on parity with the online version.
Such that shapes and stencils can be added to the library from non-native formats such as Visio. This seems to work perfectly in the online edition and I don't understand why there is a limitation of the desktop edition, be it technical or design decision.

**Describe alternatives you've considered**
I've considered using the online version but the desktop edition works better in my workflow.

**Comment by davidjgraph** [comment]
The legacy binary format requires a server to convert to the modern XML format used since Visio 2013. Load the legacy format up in a version of Visio 2013 or later and save in the modern format. That will then import unless there are EMF images in the file, which again requires a server.

Having external connections is outside of the scope of this project.

**Comment by jdmac87** [comment]
@davidjgraph - Nice one, thanks for the explanation, that makes perfect sense.
