### ISSUE TITLE
It is impossible to correctly place components in a sequence diagram using the snapping system

### ISSUE THREAD

**Issue by vmsh0** [jgraph/drawio-desktop#1370]
### Preflight Checklist

* [X] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
It is impossible to snap components of a UML sequence diagram to each other. Stuff will snap to completely wrong places, arrows will get mangled, and it is basically impossible to work a UML sequence diagram at all.

**To Reproduce**
Try to make any UML sequence diagram. For example, insert two Lifeline components, and try to then place a Synchronous invocation component across both of them. At the slightest attemp to move or rework any of the shapes, notice how the moved component breaks completely as the snapping system moves it to an unexpected place or the arrows get flipped around.

**Expected behavior**
Components snap to each other following sequence diagram semantics.

**Screenshots**
Step 1. Insert new Synchronous invocation component:
![image](https://github.com/jgraph/drawio-desktop/assets/1955497/c4e87e88-95d9-4ee7-9ebb-fab4c74ead8c)

Step 2. Attempt to place it across the two Lifeline components:
![image](https://github.com/jgraph/drawio-desktop/assets/1955497/fcb8caac-c54e-400b-b5f4-87937a9cbc25)

Step 3. Rework arrows to match new placement:
![image](https://github.com/jgraph/drawio-desktop/assets/1955497/ea4b453c-ffd7-4307-b00f-33c507c6e79d)

Notice how the arrow has snapped to the center of the rectangles, and there is no way at all to get it to move from there -- this is already after many attempts to drag it around that themselves have placed the arrow in various weird arrangements.

Also notice that the bottom arrow got arranged in a weird fashion by simply dragging its leftmost waypoint to the left rectangle.

This situation is basically irreversible, except by disabling the snapping system completely and arranging all the arrows by hand.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.3.7

**Desktop (please complete the following information):**
 - OS: Arch Linux / Sway

**Additional context**
No

**Comment by fmiqbal** [comment]
THIS, I also found this frustrating, but weirdly I vaguely remember that I can, and it behave more friendly too, including when I move the activation, the message should also move, and it is confirmed by this video https://www.youtube.com/watch?v=XC25MIcxwqU, from draw.io itself. And then I try to download the old version (currently I am trying on 16.4.11), and surprise surprise, it behave how I want it, not "broken" like current version (the diagrams net version too).

And for sequence, I can swap the lifelanes

Edit:
Confirmed something: all the good behaviour is missing on release version [21.1.2](https://github.com/jgraph/drawio-desktop/releases/tag/v21.1.2) last known good version [20.8.16](https://github.com/jgraph/drawio-desktop/releases/tag/v20.8.16)

https://github.com/jgraph/drawio-desktop/assets/8409391/9713d7fc-6a05-4b28-ab1c-d6f5599c2c0a

https://github.com/jgraph/drawio-desktop/assets/8409391/bc66c85c-b207-4ed2-a261-5e812818c84d

**Comment by alderg** [comment]
Can you attach your test case please?

**Comment by fmiqbal** [comment]
> Can you attach your test case please?

I am sorry but I think I already attach the difference as seen on the video I attach, may I know what is more information do you need ?

**Comment by alderg** [comment]
The actual diagram file so we can check what styles the cells have.

**Comment by fmiqbal** [comment]
Now that you mention it, I notice that the one created by the 20.8.16 version still behave correctly when opened with drawio version 21.6.8

[created_by_20-8-16.drawio.txt](https://github.com/jgraph/drawio-desktop/files/12392855/created_by_20-8-16.drawio.txt)
[created_by_21-6-8.drawio.txt](https://github.com/jgraph/drawio-desktop/files/12392856/created_by_21-6-8.drawio.txt)

**Comment by alderg** [comment]
OK, this is the expected behaviour, ie. it's a feature, not a bug. Existing files are not changed. The new styles try to keep the arrow segments in sequence diagrams orthogonal. You can change this by applying the old styles to the new shapes.

**Comment by fmiqbal** [comment]
Ok so indeed I think I can replicate the arrow behavior on `message` arrow, by changing waypoints to straight, but It doesn't "stick" to the activation box as the previous version, like when I stretch the activation box, the arrow that goes into (`message`) / coming out from (`return`) the activation box just stay at that point, not following the length of activation box.

![image](https://github.com/jgraph/drawio-desktop/assets/8409391/64bf0e6a-6f3d-4b3c-8104-b8e735a7b264)


Also, how about the swap behaviour? it's not present even if i copy paste the old diagram to the new version

**Comment by alderg** [comment]
Can you please add a test case for the message arrow?

The swap behaviour has been replaced with the Swap button in the Arrange panel in v21.6.9:

<img width="583" alt="Screenshot 2023-08-24 at 16 16 13" src="https://github.com/jgraph/drawio-desktop/assets/921200/87c7253c-3763-4bd3-b3f4-f780502450a2">

**Comment by fmiqbal** [comment]
Thank you for the swap button, but i still prefer the old way, but ok.
for the message arrow

From UML template, pick Synchronous Invocation
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/d194fb8d-6ade-445e-84a9-e881f7658dc8)

Add activation bar on the left side, and attach the end of the arrow (left side)
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/cbdcc2a2-7c04-45ee-a7d1-448d8c35fa1b)

Expected: the arrow didnt move, and it attach itself to the activation bar (20.8.16)
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/a71fab75-ba44-4a2a-9834-944895deb908)

Actual: the arrow move to the center
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/4107ff73-ff4a-4236-a35c-b0d9f6067816)

This can be workaround-ed by 1) change the waypoint of the line to straight and 2) move the arrow to attach to green box of the activation bar,
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/a0ef9e68-f6cc-40a7-854e-5df8d10d616d)
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/15133213-1aed-4346-a4c9-d1b19ebce143)

By doing the workaround. 1) the left side of the arrow can "stick" to the leftside activation bar, 2) it follow the right activation bar shrinking 3) stretching

![image](https://github.com/jgraph/drawio-desktop/assets/8409391/d24ced31-124d-4a15-9ac6-d567f6d3d05a)
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/638ea78a-8f3e-4d02-a79d-2490d1c16dcf)
![image](https://github.com/jgraph/drawio-desktop/assets/8409391/48d25f26-2916-471e-9c0a-23e0057abd59)


The problem is, its tedious (except maybe I can put this to scratchpad), and the green box have some I think random ? "snapping" behaviour, so its because it can basically attach it to everywhere inside the activation box, but I want the arrow to stick to the topmost of the activation box.

**Comment by davidjgraph** [comment]
Improvements implemented in 21.7.1.

**Comment by s-geiger-si** [comment]
Just found this bug, I am using v30.3.6 and frequently run into this issue when drawing sequence diagrams. I would like to use the snapping feature to snap to the the activation bar using the blue frame rather than the green frame. I observe two issues:

1. Getting to snap to the blue frame is quite difficult, as most of the time the green frame is visible and there exist only small regions where I can move with the mouse to bring up the blue frame.
2. Frequently but not always, connectors suddenly snap to the vertical center of an activation bar, I can manually move them back to the right vertical position, but then the connection end-points change to a solid blue circle, instead of the blue circle with a white ring embedded.

**Comment by davidjgraph** [comment]
Please open a new ticket with a video of the problem. This issue was deemed fixed. It might have regressed, but we need to handle that in a new issue.
