### ISSUE TITLE
The font size is incorrect

### ISSUE THREAD

**Issue by boPD** [jgraph/drawio-desktop#1448]
### Preflight Checklist

* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
When I enter text, the font size shown in the text interface tab is different from the actual size. The unit should be px not pt. In fact, it's true that pt units are used more often, so the font size shown in figure should be amended.

**To Reproduce**
1. Insert a shape
2. Double click to enter text
3. Click text interface tab
4. See the incorrect fontsize

**Expected behavior**
The font size shown in figure should be amended.

**Screenshots**
![image](https://github.com/jgraph/drawio-desktop/assets/95061491/252e2cb1-595b-4134-b662-fc6211a6e108)

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 21.6.8

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by Dfsdel** [comment]
**The font size shown in the text interface tab is different from the actual size.** The unit should be px not pt. In fact, it's true that pt units are used more often, so the font size shown in figure should be amended.

**Comment by boPD** [comment]
邮件已收到

**Comment by m-mohamedin** [comment]
Can you please share the file containing the incorrect font size?

**Comment by Dfsdel** [comment]
> Can you please share the file containing the incorrect font size?
Sorry, we just found the problem and haven't found a solution yet!  I don't have the correct font file, etc

**Comment by Dfsdel** [comment]
> Can you please share the file containing the incorrect font size?

Sorry, we just found the problem and haven't found a solution yet! So I don't have the correct font file, etc

**Comment by boPD** [comment]
邮件已收到

**Comment by mykappa** [comment]
Why won't this be fixed? I think this is a fundamental error that severely restricts the compatibility of draw.io. For example, if you export an SVG with text in size 10pt according to the draw.io UI, the actual text size is only 7.5pt, as one can discover when opening the file with Inkscape, for example. 

I see three possible solutions here:

1. leave the text sizes as they are now and introduce the label "px" instead of "pt" (ok solution)
2. adjust the text size so that it actually corresponds to the displayed size in pt (multiplication by a factor of 4/3) (good solution)
3. introduce an option with which the unit of the text size can be selected between px and pt (optimal solution)

**Comment by mikochergin** [comment]
The bug is still actual (v. 24.2.5). If past text 14 pt into draw.io scheme, it shows 18.867 pt. Text typed in draw.io as  14pt is smaller than text from Word. But text typed in draw.io as 16 pt has exactly the same size as text 14pt from Word.
[Font bug.zip](https://github.com/user-attachments/files/17125827/Font.bug.zip)
![image](https://github.com/user-attachments/assets/c9f372bb-5b3e-4f9f-8a6a-26f6e2ac94b3)

**Comment by boPD** [comment]
邮件已收到
