### ISSUE TITLE
Exporting PDF does not have background

### ISSUE THREAD

**Issue by patefoniq** [jgraph/drawio-desktop#1583]
Like in the topic. After exporting the diagram with a color background, the PDF file has a white background. The same happens while printing the document.

I have desktop version: 22.1.18

**Comment by LinguaOccultus** [comment]
I can confirm this also. I just switched from colored rectangles as a background to the color background feature since it seemed the other method had some drawbacks. But creating a PDF does show only a white background and ignores this setting completely. Tried around a bit with the settings but nothing seems to affect it in any way. Putting a colored rectangle in the background instead, of course, works again immediately.

I cannot tell if earlier versions had this issue also or if it is a new one. Since I was having this issue only 1-2 minor version came out and it persists. All documents show the same behaviour so it does not seem to be related to the file in any way.

Current version: 22.1.18 (latest while writing this post)

**Comment by LinguaOccultus** [comment]
Just found out that printing a file shows the same problems with font colors as exporting as PDF (I do not print often).

As I am using the dark mode be default, this reminds of the trouble we had with that affecting the colors in the drawing some time back already. Maybe the same again?

**Comment by kreon0** [comment]
I see the same issue with PDF export and background colors.

In particular, I have a table and if I add background color to text in a table cell, it's not exported to the PDF (also not when printing to PDF).

I just checked: it works with v22.1.11 and stops working with v22.1.15
I also tried v22.1.16 and v23.0.2 (latest), where it's also not working.
I'm using the "Windows No Installer" version on a Windows 11 Pro 64bit machine.

**Comment by gblomqvist** [comment]
Also affects the AppImage, starting with version 22.1.15, up to and including the latest version (23.0.2). Perhaps related to #1576, which also affects the same versions.

**Comment by airlomba** [comment]
One more guy here, not getting background color, when exporting to PDF.
v22.1.16 on Linux
Regards,

**Comment by alderg** [comment]
Try v24.4.8. https://get.draw.io/

**Comment by patefoniq** [comment]
After update to the current release (v24.4.13), the problem disappeared. Post can be mark as solved/fixed.
