### ISSUE TITLE
Plugins work only once after reload

### ISSUE THREAD

**Issue by zahdimar** [jgraph/drawio-desktop#1619]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Plugin doesn't work after 2 reloads. When you add plugin (Extras - Plugins - Add) it has path like `plugins/trees/trees.js`, but it doesnt work until reload. After reloading it works, but it has path `./plugins/trees/trees.js`. After next reload you have path `./plugins/trees/trees.js` and not working plugin.

**To Reproduce**
1. Go to 'Extras - Plugins'
2. Add some plugin, check the path. It should be like 'plugins/...'
3. Close application
4. Open some already existed .drawio file from file explorer
It doesn't reproduce, if you open file from `File - open` or `File - Open recent`
5. Check that plugin is working and it path has changed './plugins/...'
6. Reload application
7. Check that plugin doesn't work and it path has changed
 path './plugins/...'

**Expected behavior**
After opening files from anywhere you have working plugins

**Screenshots**
step 2
![image](https://github.com/jgraph/drawio/assets/10091245/d1b3ae1c-7764-45c6-974f-e85822b2c637)
step 3
![image](https://github.com/jgraph/drawio/assets/10091245/9d6fb789-c5c2-4834-9b5c-9162187be235)
step 4
![image](https://github.com/jgraph/drawio/assets/10091245/035e6c9e-cf42-4975-9ec8-09f0e168cfdb)

- draw.io version 23.0.2

**Desktop (please complete the following information):**
 - OS: windows 11 (23H2 + russian OS language)
 - Desktop application
 
**Additional context**
I had almost the same issue several month ago and it was fixed but it appears one more time...
https://github.com/jgraph/drawio/issues/3395

**Comment by ariel-bentu** [comment]
Hi,
I can add some info on the cause:
- after installing a plugin, it is saved with full-path `file://<full-path-to-js-file>`
- In App.main, [here](https://github.com/jgraph/drawio/blob/ea7a1cb21435e411a724e85420126966f7671766/src/main/webapp/js/diagramly/ElectronApp.js#L155) the loading code assumes that it is a path starting with plugins or else it calls getPluginFile:
```
let pluginFile = await requestSync({
  action: 'getPluginFile',
  plugin: plugins[I]
  });
  ```
  which in turn assumes it is a file-name only see [here](https://github.com/jgraph/drawio-desktop/blob/6374d2fce4f4efe962730b5ecc10d89b5f869ca6/src/main/electron.js#L2316)


so the issue is either when storing the plugin file in the settings as full-path or at processing it no considering that it is a full-path

**Comment by m-mohamedin** [comment]
Please try the new release 12.4.0
