### ISSUE TITLE
`--crop` not working as expected on latest versions

### ISSUE THREAD

**Issue by rosseljost** [jgraph/drawio-desktop#1759]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.
  * there are related topics being discussed in jgraph/drawio-desktop#1747 and jgraph/drawio#4464 but the report seems different from my point of view

You must agree to search and the code of conduct. You must fill in this entire template. If you delete part/all or miss parts out your issue will be closed.

**Describe the bug**
The `--crop` parameter does not actually crop the image to the smallest dimensions, depending on the version.
I noticed the bug in 24.4.8 and a different wrong behavior in 24.4.0, 24.2.5 works as expected.
- 24.4.0 seems to use the page size from the drawio file
- 24.4.8 looks like an A4/letter page

**To Reproduce**
1. Export ![confidentiality.drawio](https://github.com/jgraph/drawio-desktop/assets/44645301/f4409215-612f-4d95-a5f3-88437c5c226b) (not actually an SVG, just renamed the .drawio XML file so that I can upload it) using
   ```
   drawio -x -e -o "confidentiality.pdf" -f pdf --crop -t "confidentiality.drawio"
   ```
2. Compare the resulting PDF on different version.

**Expected behavior**
The behavior from 24.2.5

**Screenshots**
My results:
   1. [confidentiality_24.2.5.pdf](https://github.com/jgraph/drawio-desktop/files/15482797/confidentiality_24.2.5.pdf)
   2. [confidentiality_24.4.0.pdf](https://github.com/jgraph/drawio-desktop/files/15482796/confidentiality_24.4.0.pdf)
   3. [confidentiality_24.4.8.pdf](https://github.com/jgraph/drawio-desktop/files/15482798/confidentiality_24.4.8.pdf)

**draw.io version (In the Help->About menu of the draw.io editor):**

- at least draw.io version 24.4.0 and 24.4.8, but possibly more

**Desktop (please complete the following information):**
 - OS: Linux ([Arch Linux binary build AUR](https://aur.archlinux.org/packages/drawio-desktop))

**Comment by alderg** [comment]
I checked your test case on v24.4.8 with macOS and Windows and those are working. Are you sure you are using v24.4.8? (Check with `draw.io --version`)

**Comment by XoMEX** [comment]
Can reproduce on Arch (https://aur.archlinux.org/packages/drawio-desktop version 24.4.8-2; `drawio --version` reports it as 24.4.8)

**Comment by rosseljost** [comment]
this is what I did to get the files in the original issue:

```
drawio -x -e -o "confidentiality_$(drawio -V).pdf" -f pdf --crop -t "confidentiality.drawio"
```

while switching between cached (i.e. previously built) versions of drawio using my package manager.


I just asked a colleague of mine to run that command. He could not reproduce on NixOS using version 24.4.0

**Comment by davidjgraph** [comment]
I cannot repeat on the .deb build on an ubuntu flavour. The question is whether the problem is with arch linux specifically, or with the arch linux build.

But given none of us run arch linux and we have never had anything to do with the arch linux build, I think this would be better directed at whoever authors the arch build.

**Comment by dvalter** [comment]
@davidjgraph I was able to reproduce this by running on `v24.4.8`
```bash
yarn install
yarn run sync
yarn run release-linux
```

After unpacking from release .deb and from `dist/linux-unpacked/resources/`, the only substantial difference is `drawio/src/main/webapp/js/app.min.js`.

Looks like it has not been updated in open source drawio [since v24.3.1](https://github.com/jgraph/drawio/blob/dev/src/main/webapp/js/app.min.js) and this it what makes source-based builds broken.

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop shows the correct submodule. Are you sure submodules are being recursively pulled on updates?

**Comment by davidjgraph** [comment]
OK, no, you're right. There's an update problem with that file. Amazing nobody else noticed :D.

**Comment by dvalter** [comment]
They are. However that won't help without rebuilding `app.min.js` from up-to-date source.

I've added `ant app` to the AUR PKGBUILD and it has seemingly fixed the issue.

As for your packages, Github CI workflows use the private drawio-dev rather than the public drawio repo, and it likely makes all the difference.

**Comment by davidjgraph** [comment]
OK, thanks for the investgations, we'll get the public repo fixed.

**Comment by davidjgraph** [comment]
OK, deploy process fixed.
