### ISSUE TITLE
CMD+Alt+Shift+V does not work on MacOS

### ISSUE THREAD

**Issue by ndsvw** [jgraph/drawio-desktop#204]
There are 2 possibilities to paste some text on MacOS:
- CMD+V (pasting and keeping the copied style in the text)
- CMD+Alt+Shift+V (pasting and ignoring the copied style in the text)

CMD+Alt+Shift+V does work on the draw.io website but it does not work in the desktop app.

**This is what I expect (it works on draw.io):**
![1](https://user-images.githubusercontent.com/21332313/72872680-3490a880-3cee-11ea-98d2-63c0c233eb00.gif)

**This is what happens using the desktop app. CMD+Alt+Shift+V does nothing:**
![2](https://user-images.githubusercontent.com/21332313/72872717-50944a00-3cee-11ea-897c-4e5815d6be8f.gif)

CMD+Alt+Shift+V is useful on MacOS. If it does not work, the style of the text will always be pasted after copying some text with style information.

**Comment by davidjgraph** [comment]
Haven't found a way this can be done in Electron, VS has the same problem. If anyone knows better, open to PRs.

**Comment by rynkevich** [comment]
Hello @davidjgraph, @ndsvw 
I've created a [PR](https://github.com/jgraph/drawio/pull/836) to add this feature to macOS. \
\
It looks like macOS version of app has more troubles with shortcuts. I've noticed that Cmd+A (Select All), Cmd+Shift+Z (Redo) and right mouse button click to get a pop-up menu don't work in text editing. It is strange, especially in case of "Redo", because "Undo" works just fine. Tried with the latest build (12.9.3), macOS Catalina 10.15.3.

**Comment by rynkevich** [comment]
Ping! Is this issue still relevant?
@davidjgraph

**Comment by ashrafteleb** [comment]
Thanks for the fix and sorry for the delay
PR merged and will be available in the next release

**Comment by ashrafteleb** [comment]
BTW, do you how to fix the other shortcut issues you mentioned?

**Comment by rynkevich** [comment]
@ashrafteleb, thanks!
I think that other issues could be fixed the same way I've added "Paste and Match Style" feature. I can try to do this and provide a PR.

**Comment by rynkevich** [comment]
Hi @ashrafteleb,
I've created a PR with features that are missing on macOS.
https://github.com/jgraph/drawio/pull/891 (Redo + Select All)

As for context menu, Electron doesn't have a built-in solution, but there is a popular package that solves that problem. I've provided it in separate PR because I don't know if a new dependency is OK for you.
https://github.com/jgraph/drawio/pull/892

**Comment by ashrafteleb** [comment]
@rynkevich Thanks a lot for your help

**Comment by rynkevich** [comment]
@ashrafteleb @davidjgraph 
Glad to help.
I expected that there could be problems with an extra dependency. How about creating a new "help wanted" issue to provide an internal implementation for context menu? Probably, I'll return and implement it or somebody else will pick it up.

**Comment by davidjgraph** [comment]
Ah, new issue, sure, that works. Thanks again.
