### ISSUE TITLE
Windows Portable Version

### ISSUE THREAD

**Issue by RoyiAvital** [jgraph/drawio-desktop#22]
Hello,

Could you please add a portable version for Windows?

Portable means:
 * All settings and temporal files are self contained in the program folder.
 * It doesn't use any registry keys.
 * Doesn't require privileges.

Easy way to do so is using the @PortableApps framework.

Thank You.

**Comment by davidjgraph** [comment]
Added https://github.com/jgraph/drawio-desktop/releases/tag/v10.7.5

**Comment by RoyiAvital** [comment]
@davidjgraph , This is great news.

I can see `draw.io-10.7.5-windows-portable.exe`. Could you explain it?
Is it an EXE or is it an installer?

Thank You.

**Comment by davidjgraph** [comment]
We added https://github.com/jgraph/drawio-desktop/blob/master/electron-builder.json#L23 and that exe popped out. According the to https://www.electron.build/configuration/win it's not an installer, but I'm not a big windows user, maybe someone could check it?

**Comment by jingyu9575** [comment]
Hi, I did not find the portable exe file. Could you have a check?

**Comment by davidjgraph** [comment]
windows-no-installer

**Comment by jingyu9575** [comment]
@davidjgraph I see. Thank you!

I originally thought that `windows-no-installer` is the version with the program self contained, but still use the data in the user's home; I was expecting another `portable` version that has both program and data self contained, as OP says:

> All settings and temporal files are self contained in the program folder.

Looks like this is not supported yet.

**Comment by davidjgraph** [comment]
It's the portable version out of electron-builder, https://www.electron.build/configuration/win. We're not going to customize EB, so if there's a requirement on it, the original project is the best place to search/submit.

**Comment by nikhilgupta-repos** [comment]
I was looking for a portable version and after much looking, I ended up using a switch while launching the application.
`--user-data-dir=<data_path>`
This way it becomes a self contained app.

**Comment by Reveanime** [comment]
> `--user-data-dir=<data_path>`
I add the parameter `--user-data-dir=<D:\Program Files\Draw io\Data>` to the end of target in the shortcut，but it does not work. Can you give more details?

**Comment by andzi** [comment]
> > `--user-data-dir=<data_path>`
> 
> @nikhilgupta-repos
> I add the parameter `--user-data-dir=<D:\Program Files\Draw io\Data>` to the end of target in the shortcut，but it does not work. Can you give more details?

Probably you shoul put path into quotes: --user-data-dir="D:\Program Files\Draw io\Data"

**Comment by RoyiAvital** [comment]
Is there a reason the `--user-data-dir=<data_path>` flag doesn't support relative paths?

**Comment by ariefcfa** [comment]
here is the steps to have full portable draw.io desktop on Windows 10 (tested and working, but I have no idea if this is correct)
1. Download draw.io `Windows No Installer`
2. run the `draw.io-16.5.1-windows-no-installer.exe`
3. (it will create temporary files inside random named folder in `"C:\Users\<username>\AppData\Local\Temp\<random folder name>"`)
4. while draw.io still running, copy all the temporary files mentioned in step 3 to the preferred location, for example: `"F:\drawio\app"`
5. copy all draw.io user data files in `"C:\Users\<username>\AppData\Roaming\draw.io"` for example to `"F:\drawio\data"`
6. Create shortcut to draw.io.exe, in this case located in `"F:\drawio\app\draw.io.exe"` where:
target: `"F:\drawio\app\draw.io.exe" --user-data-dir="F:\drawio\data"`
start in: `"F:\drawio\app"`

this shortcut also can be pinned to taskbar

7. redo step 4 when update draw.io. The `draw.io-16.5.1-windows-no-installer.exe` is safe to delete afterward

for me, the main reason doing this hassle is as anticipation if must reinstall Windows. Seems the other benefit is reduced disk write when running draw.io desktop, because draw.io will create temporary files when launched and delete them when closed (this cycle repeat). Cheers

credit to: @nikhilgupta-repos [https://github.com/jgraph/drawio-desktop/issues/22#issuecomment-703295139](https://github.com/jgraph/drawio-desktop/issues/22#issuecomment-703295139)

Additional notes:
To have working open file from Windows Explorer, try use [https://www.nirsoft.net/utils/file_types_manager.html](https://www.nirsoft.net/utils/file_types_manager.html):
1. Edit > New File Extension
Extension: `.drawio`
Default icon: locate the `draw.io.exe`
2. Press OK
3. Select the newly created `.drawio` extension
4. Actions > New Action
Action Name: `Open`
Command-Line: `"F:\drawio\app\draw.io.exe" "%1" --user-data-dir="F:\drawio\data"`
5. Press OK

**Comment by crimsonduelist** [comment]
Couldnt u just grab the no-installer release and use 7zip to extract the app64 folder for example and use a shortcut with the aforementioned flag `--user-data-dir="C:\Path\To\MyFolder`.
Is smthing not configured properly without running the .exe?

**Comment by RoyiAvital** [comment]
Now there is a portable version in [PortableApps](https://portableapps.com/).
Probably the best way to have this in a portable version.
