### ISSUE TITLE
drawio snap cannot access removable media

### ISSUE THREAD

**Issue by karimmd** [jgraph/drawio-desktop#353]
I have tried to plugin the removable media through snap connect option but it was not working.

**Comment by mararad** [comment]
Hi,

What exact steps did you perform? What desktop app version are you using (can be seen under Help)?

Regards,

**Comment by karimmd** [comment]
The permission to removable-media is not present in draw.io which would not allow users if they want to modify or store files in other than /home/user directory.

For example, please look at the snap permission of vlc

![image](https://user-images.githubusercontent.com/6984392/90072446-fe6a5300-dd29-11ea-9c3e-0e9dfe0f9e84.png)

Compare to drawio, its missing, therefore, we can not access any files from USB pendrive or harddrive because drawio snap app does not have access to /media

![image](https://user-images.githubusercontent.com/6984392/90073335-94eb4400-dd2b-11ea-8380-a6563048b565.png)


You can have a look on the official snapcraft page

https://snapcraft.io/docs/removable-media-interface

**Comment by KhaledOmara** [comment]
@karimmd Should we do anything from our side to fix this, or there will be a release to add the permissions?.

**Comment by karimmd** [comment]
> @karimmd Should we do anything from our side to fix this, or there will be a release to add the permissions?.

I have switched to deb package of draw.io

**Comment by pboissonneault** [comment]
I've installed drawio with the --devmode option and I now have access to removable-media

`sudo snap install drawio --devmode`

**Comment by karimmd** [comment]
How --devmode is different than using --classic, anyone have any ideas......

**Comment by karimmd** [comment]
> I've installed drawio with the --devmode option and I now have access to removable-media
> 
> `sudo snap install drawio --devmode`

Let me try that. Thanks for your feedback.

**Comment by pboissonneault** [comment]
Another workaround is to create a `symlink` in your home directory to the data you need to access.

**Comment by ASLanin** [comment]
> Another workaround is to create a `symlink` in your home directory to the data you need to access.

Did you try this?
I ask because I have the same issue. ~/Downloads -> /media/LinExt/Downloads/ symlinked on my laptop. And it is impossible to start draw.io, even for the first time.  

>I've installed drawio with the --devmode option and I now have access to removable-media
It sounds too straight  design.  `devmode` turn off any Snap restriction. Allow access to removable media != allow full access.

Looks like Removable-media interface could be added by developers, as mentioned there https://snapcraft.io/docs/snapcraft-interfaces

**Comment by daandres** [comment]
is there any update on this?

**Comment by flippipe** [comment]
Using [Snap Try](https://snapcraft.io/docs/snap-try) I've changed the snap.yaml to add `removable-media` and it works as expected. But doing this every time there is a new release is cumbersome.

After digging around, I've found, probably, it is only need to add
```json
"snap": {
  "plugs": [
    "default",
    "removable-media"
  ]
}
```
to [electron-builder-snap.json](https://github.com/jgraph/drawio-desktop/blob/dev/electron-builder-snap.json) in order to electron build the snap with `removable-media` interface enabled, as other [projects](https://github.com/mifi/lossless-cut/blob/master/package.json) already do it.

I hope this information helps fast forward the fix of this issue.

**Comment by chrispito** [comment]
> I've installed drawio with the --devmode option and I now have access to removable-media
> 
> `sudo snap install drawio --devmode`

It worked for me! Thank you

**Comment by MaurizioCasciano** [comment]
Running `snap connect drawio:removable-media` solved the problem for me.

**Comment by davidjgraph** [comment]
We've added the suggested build config. I don't see any other suggestions in the thread, so I will close with the workaround being to `run snap connect drawio:removable-media` if you can't get it working another way.
