### ISSUE TITLE
"Save as" over-writing original file

### ISSUE THREAD

**Issue by npodonnell** [jgraph/drawio-desktop#377]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**

"Save as" feature over-writing original file. This is quite annoying on a project I'm working on, since I have to keep `git checkout`'ing the overwritten files to restore them.

**To Reproduce**
1. Open draw.io desktop, Create New Diagram
2. Draw something, eg. a square
3. **File -> Save** and name the file as *x.drawio*
4. Draw something else, eg. circle
5. **File -> Save As** and save as *y.drawio*
6. **File -> Open** and open *x.drawio*
7. *x.drawio* will have a square and a circle.

**Expected behavior**
*x.drawio* should have only a square.
*y.drawio* should have a square and a circle.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 13.6.2

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by ashrafteleb** [comment]
You'll need to disable autsave in order to get the expected behavior.
In your example, when the circle is added, it is saved to x.drawio by autosave

**Comment by npodonnell** [comment]
I think this is confusing UX. 

Most traditional desktop apps which have a save / save-as don't auto save by default, users don't expect this behavior.

Maybe consider turning off auto save. When it's turned on, remove or disable the Save feature so users don't lose work like I did.

**Comment by DomHudson** [comment]
I agree, this behaviour is counter-intuitive and in some cases quite damaging. For example, if I wanted to produce two similar diagrams:

1. I draw the first diagram
2. I "save as" with one name.
3. I alter the diagram to produce a new one
4. I "save as" with a new name.

Other programs would have the two states saved in the two different files, but this behaviour means that both files are identical containing all changes.

**Comment by DomHudson** [comment]
I agree, this behaviour is counter-intuitive and in some cases quite damaging. For example, if I wanted to produce two similar diagrams:

1. I draw the first diagram
2. I "save as" with one name.
3. I alter the diagram to produce a new one
4. I "save as" with a new name.

Other programs would have the two states saved in the two different files, but this behaviour means that both files are identical containing all changes. 

This exact thing happened to me: I had to recreate the first diagram and whilst doing this, the software overwrote the second diagram again.

**Comment by ashrafteleb** [comment]
As we mentioned before, the app is set to auto save by default. So, any changes done up to the point of the "save as" are automatically saved to the first diagram. Once you saved as a new one, the changes are only added to the new one.

To change that behavior, disable auto saving.

Let us know if we get it wrong

**Comment by ashrafteleb** [comment]
@npodonnell disabling autosave will cause more issues when work is lost. Check online editors like office or Google document, they auto save and also have a save as

**Comment by npodonnell** [comment]
@ashrafteleb This is a desktop app. It's called drawio-desktop. It's not an online editor. Take a look at Photoshop, Gimp, Inkscape, the list goes on. These are similar to draw.io and they are all desktop apps and they do not auto save.

At the very least - disable or remove the save item in the menu if you want to keep the confusing UX, because it has no effect.

**Comment by hviridis** [comment]
Today I am glad to notice that with diagrams.net 13.9.9 the **misleading dialog on quit** (about to save or to discard changes) while autosave option is enabled apparently **does not appear anymore.** I experienced the dialog with draw.io 12.4.

Formerly I did not notice that the desktop app came with an autosave option and this option was enabled by default. When I finished the drawing I intended to export it to a commonly known format like pdf. **As the application does not support to define how content should be arranged on multiple pages the user must select the objects to come onto each page** and delete anything else. This is why I had to split up the document by "save as" and while I was applying final adjustments I faced the unexpected autosave behaviour. Even backup could not remedy. **I suppose I won't be the last one that will fall for it.**

Meanwhile the desktop app was slightly improved. However, **I still regard the autosave implementation as disadvantageous.** At least some kind of **version control should be supplemented** as undo/redo-cache is discarded on quit. Autosave feature should protect the user from unexpected data loss, e.g., with an online application in case of a network connection fault. Program termination in contrast to manually save a document might occur intended or unintended. An unintended term signal may lead to unexpected data loss as well, e.g., reboot is automatically initiated (I feel an extraordinary love on how the developers care to silently apply updates to Microsoft Windows).

_Traditionally_ autosave feature has been accomplished by a hidden copy of the document and user intension is confirmed by manual save function. In case a user confirmation is missing on start of an application the user is asked if previous state should be restored (libreoffice, vim). This method can be found with online and with offline applications.

_Nowadays_ some application concepts take a simplified approach and abandon manual saving (Etherpad, JetBrains Rider). This is as collaboration tools reasonably feature version control which requires regular or continuous synchronisation to cope with potential conflicts. Even applications that deal with single-state data like accounting system usually have at least rudimentary version control (automatic backups, recovery points).

I propose:
* If save button should persist it at least should be greyed out to immediately indicate autosaving. Alternatively it would be reasonable to adopt the menu entry to create a snapshot with a timestamp that is stored as part of the document.
* If autosave is enabled save button should be removed and "save as" should be renamed to "create a file copy and edit..." in order to provide an intuitive usage.

**Comment by wmjordan** [comment]
I came from issue #588 to here after upgrading from a very old version of draw.io.

It is not a very big deal to provide an option to disable this horrible, panicky behavior on the desktop version--why it is Low Priority?

**Comment by codebling** [comment]
Disabling Autosave is good enough for me, though I can see that not everyone in here feels the same way. Perhaps if the Autosave checkmark was in the File menu beside the Save options, the current behavior would be more obvious and take fewer people by surprise.

**Comment by m-mohamedin** [comment]
In the next release, auto-save would be disabled by default. To prevent data loss, changes would be saved in an internal draft in case app had crashed or machine is turned off.

**Comment by davidjgraph** [comment]
Attempt to address this in 16.0.0. Feeback welcome.

**Comment by codebling** [comment]
Tested it out. Looks great! I see that autosave is disabled by default, now. "Unsaved changes" shows up as soon as any change is made, and with autosave disabled, my regular workflow operates as expected.

**Comment by codebling** [comment]
New build looks good, thanks! Can't find any obvious bugs. In terms of other feedback, I like the idea of the 'autosave' checkbox being in the File menu, nearish the Save options, though maybe there's a technical reason for it being in the Extra menu.

Thanks for all of the hard work!

**Comment by wmjordan** [comment]
> To prevent data loss, changes would be saved in an internal draft in case app had crashed or machine is turned off.

If we don't want **each action** leads to auto-saving to a draft, can we control the auto-save as a postponed one--unsaved drafts are backed up periodically?

**Comment by codebling** [comment]
> 
> If we don't want each action leads to auto-saving to a draft, can we control the auto-save as a postponed one?

If Auto-save is on, it works as it did before. If Auto-save is off and changes are made to the open file, it saves a backup file (does not overwrite open file), and if the application crashes and the original  file is opened, a dialog pops up showing unsaved changes from the last session. @wmjordan it sounds like you want to completely disable this functionality? (...why?)  

btw ashrafteleb davidjgraph I tested the "internal/draft" autosave and it works like a charm. Nice work

**Comment by wmjordan** [comment]
Hi, @codebling , I am not supposed to disable the auto-save backup file feature completely.
I would like the auto-backup function is run at a several-minutes' interval, not after each change. Otherwise, it will consume much battery on my notebook.

**Comment by codebling** [comment]
It looks like there's already [a debounce of 1.5 seconds, with a maximum interval of 30 seconds between autosaves](https://github.com/jgraph/drawio/blob/c02986677e97035007c4fb0221363441045e0283/src/main/webapp/js/diagramly/DrawioFile.js#L85-L91)

**Comment by wmjordan** [comment]
That option might not be what I need. It controls the auto-save, but now it is no longer the problem. The option in question is _**auto-backup**_, which is new to version 16. Like Microsoft Office, it has a configurable value of auto-recovery, and by default, it backups unsaved document every 10 minutes.

**Comment by m-mohamedin** [comment]
@wmjordan Currently there's no configuration for that. Please open a feature request issue.

Also, please let us know if you noticed a degradation in battery performance using the new version.

Thanks

**Comment by wmjordan** [comment]
@ashrafteleb 
Thank you for replying. I will monitor the file system, see how draw-io behaves and open an issue when necessary.
