### ISSUE TITLE
Shortcuts not working with alternate modifier keys in Mac OS X

### ISSUE THREAD

**Issue by rgoya** [jgraph/drawio-desktop#38]
I am trying to use draw.io on Google chrome on a Mac, but cannot use shortcuts.

As part of my desktop setup I have changed the location of the command and control modifier keys. Every application I use correctly handles this, except draw.io. It would seem that draw.io is ignoring the system's defined modifier keys.

I have verified this is the problem by briefly changing my modifier keys to the standard; however, this is not a sustainable solution because I have changed the keys for a reason in the first place!

It would be great if draw.io could recognize the OS-defined "cmd" and "ctrl" keys instead of fixating on the usually-defined keys.

**Comment by Preskton** [comment]
I'm experiencing the same behavior. I've attached a PC keyboard to my Mac and have remapped the keys to more closely align to a normal Mac keyboard. When I press my `command `key + `X` to cut, draw.io does not cut.

Here is my configuration:

![image](https://user-images.githubusercontent.com/6252405/57231273-d5fc9080-6fdf-11e9-99a8-06b854e82e09.png)

**Comment by ffffwh** [comment]
Same for me. Currently my workaround is using cmd-drag to duplicate an item.

**Comment by xinatcg** [comment]
same issue

**Comment by javadba** [comment]
This issue is still present March 2020

**Comment by davidjgraph** [comment]
@javadba Yes, that's why the issue is still open. Please only comment if it adds anything to the thread.

**Comment by NickTruesdale** [comment]
Same issue. For some reason my right command key does work though - it's just the left key that does not. But that's not helpful when the common workflow is right hand on mouse, left hand on copy/paste duty.

The edit menu in the Chrome toolbar flashes when I hit cmd+c, so it's clearly registering it. But draw.io does not see it.

This seems like a relatively easy issue to reproduce and troubleshoot - it'd be good to get a response, since it's been reported by many users in multiple issue threads. Is it harder to fix than it seems?

**Comment by javadba** [comment]
I have mentioned in March before I also do have this issue  that using Command-C sometimes just does not work.  The comment was deleted by @davidjgraph  - but the issue remains.  The contents of the clipboard are not updated with the selected elements.  

Here is a youtube video of the problem.    https://youtu.be/yoheGga5Hik

**Comment by ashrafteleb** [comment]
Closed of https://github.com/jgraph/drawio-desktop/issues/2
