### ISSUE TITLE
Snap is classic and has network connection

### ISSUE THREAD

**Issue by j5awry** [jgraph/drawio-desktop#384]
According to documentation for this project, Drawio Desktop is designed to be completely isolated from the internet. However, the latest snap shows a network connection. This is related to creating a classic snap. Considering the security statements, it makes sense for drawio-desktop's snap to move to [strict confinement](https://snapcraft.io/docs/snap-confinement) with specific interfaces listed. Below is a readout of the connections open for drawio.

```
 snap connections drawio
Interface                 Plug                    Slot                             Notes
audio-playback            drawio:audio-playback   :audio-playback                  -
browser-support           drawio:browser-support  :browser-support                 -
content[gnome-3-28-1804]  drawio:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     drawio:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      drawio:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     drawio:sound-themes     gtk-common-themes:sound-themes   -
desktop                   drawio:desktop          :desktop                         -
desktop-legacy            drawio:desktop-legacy   :desktop-legacy                  -
gsettings                 drawio:gsettings        :gsettings                       -
home                      drawio:home             :home                            -
network                   drawio:network          :network                         -
opengl                    drawio:opengl           :opengl                          -
pulseaudio                drawio:pulseaudio       :pulseaudio                      -
unity7                    drawio:unity7           :unity7                          -
wayland                   drawio:wayland          :wayland                         -
x11                       drawio:x11              :x11                             -
```

**Comment by ashrafteleb** [comment]
Can you please identify which website the app is connected to?
Please note that the app can work offline but still it can connect to the internet for some functions like inserting an image from a URL. Also, no connection to draw.io is needed at all.

**Comment by j5awry** [comment]
I didn't know inserting from URL was possible.

However, based on your security docs, an "offline" install or setup of drawio-desktop should not have the capability of doing an "insert image : from URL." 

> draw.io Desktop is designed to be completely isolated from the Internet.

In Snaps, it is possible to create on isolated from the internet. Using a non-classic snapcraft.yaml, one would be able to specify interfaces at install time (such as creating a truly isolated snap, without the network automatically connected). Furthermore, users can then enable the interface at their will. The snapcraft docs show this with VLC. VLC defaults to not having the camera interface connected. However, there are capabilities of VLC that can utilize the camera. If users want this, they can enable the interface 

https://snapcraft.io/docs/interface-management

**Comment by haakonstorm** [comment]
Hey! Came here looking for the same, `Draw.io.app` (`drawio 13.7.9`) installed via homebrew: `brew cask install brewio` today, on a `macOS 10.15.7`/`iMac Pro` box. 

I learned about `draw.io` after originally searching for the best `VS Code` plugin to work with `.svg` files semi-manually/semi-visually, preferably with some form of rudimentary bidirectional update mechanism so previews reflect changes in code, but also some rudimentary UI where changes visually are reflected back in the code. The  I want to be able to programmatically create imagery, by writing macros or svg directly, but having everything in an integrated environment where I can also see the SVG rendered and do at least minor corrections with an integrated UI of sorts seeing the result, then updating either   read the [very bold] security statement about the desktop version being isolated from the interwebz, then installed via `brew`.

Upon first launch (after removing the usual `com.apple.quarantine` flag put there by macOS SIP/security), then my outbound firewall of choice, `Little Snitch`, intercepts and displays two outbound connection attempts:

<img width="551" alt="Screenshot of Little Snitch Agent (21-10-2020, 02-22-16)" src="https://user-images.githubusercontent.com/193781/96659010-40c19900-1346-11eb-9826-0410cfa271e8.png">

<img width="544" alt="Screenshot of Little Snitch Agent (21-10-2020, 02-22-30)" src="https://user-images.githubusercontent.com/193781/96659021-44edb680-1346-11eb-81c6-3942dd0fa83e.png">

If the project didn't prime me with the bold statement about sandboxing, I wouldn't have thought twice about this. But since it did, and I see this happening, it's a matter of either (A.) imprecise wording on the behalf of the secretive draw.io marketing division that should be augmented, or, (B.) the wording is precise, and the development division has lost control of parts of the code base somehow. That has happened before to software development houses. As in, after a targeted breach, black hats altered their build chain. So that on next updating their software, a root kit piggybacked along, silently installed on every user machine.

I'm just making 100% and not 99.9% sure we are on plan A. and not plan B. here.

.]  //Storm

**Comment by ashrafteleb** [comment]
draw.io make a connection to github.com to check for new releases. It is part of our automatic update process.

Official releases are here:
https://github.com/jgraph/drawio-desktop/releases

**Comment by ashrafteleb** [comment]
If you blocked all connections to the application, it will still work with full functionality (except automatic updates of course)

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio-desktop/commit/8b67a3158fca720b2adfcdc52414c2809554b7df

**Comment by j5awry** [comment]
@ashrafteleb except both of these mentions are using package managers that handle updates for us. snapd automatically updates snaps (and in the background). And when I used homebrew, I much preferred to update myself. Wouldn't it make more sense to disable auto-update for packages that have a normal update process, and close your connections?

**Comment by ashrafteleb** [comment]
homebrew release is not maintained by us (unofficial release). As for snap, auto-update is already disabled

**Comment by j5awry** [comment]
I'm happy that it's already disabled. Could you update the documentation to reflect that (you could update in the snapstore documentation itself)? And also update the documentation to reflect what interactions are possible in an isolated environment (as there is a loss of functionality in the integrations), and update https://www.diagrams.net/integrations

It looks like there are several places that will need updated in regards to what is happening for secure environments. I know this is nitpicky, but if you're working in a high security area, and every app needs to be fully vetted before use, any documentation is helpful.
