### ISSUE TITLE
Initial save does not append file extension.

### ISSUE THREAD

**Issue by Robaire** [jgraph/drawio-desktop#410]
Creating a new diagram and saving it does not automatically append `.drawio` to the file name. The `.drawio` file format is selected by default and I assume it should be used. This is inconsistent with Save As, which does automatically append `.drawio` to the file name. Tested in Ubuntu 20.04.

**Comment by Pilen** [comment]
I was troubled by this too.

I created a new diagram, did some work and clicked save
The default name is just "Untitled Diagram" with no .drawio extension, so the natural thing is to just change that part and not add the extension manually. The saved file does not show up when trying to open a file as it does not have the .drawio extension, and likewise it does not show up in the recent files. I thought i had lost a lot of files due to this.

The strange thing is that if you click save as instead of save the default name is "Untitled Diagram.drawio" with the base part preselected.

**Comment by skoehler** [comment]
This bug is fixed, I think. When I create a new diagram in 16.4.0, then it has the drawio extension.
