### ISSUE TITLE
希望出一个及时预览的功能

### ISSUE THREAD

**Issue by yaoyi2008** [jgraph/drawio-desktop#458]
希望能增加一个HTML格式的及时预览功能，这样就可以不用每次查看的时候都得先导出成HTML，然后才能再看到。

由于改动频繁，希望能改一下就能预览的话，就比较好了，尤其是针对画面比较大的图。

**Comment by Narcha** [comment]
I put this through a translator so you don't have to.
I can't guarantee accuracy since I don't speak Chinese.
# Hope to have a timely preview function
I hope to add a timely preview function in HTML format, so that you don't have to export it to HTML every time you view it, and then you can see it again.

Due to frequent changes, it is better if you can preview it after you change it, especially for larger pictures.

**Comment by Russiarain** [comment]
> 希望能增加一个HTML格式的及时预览功能，这样就可以不用每次查看的时候都得先导出成HTML，然后才能再看到。
> 
> 由于改动频繁，希望能改一下就能预览的话，就比较好了，尤其是针对画面比较大的图。

你的意思是画面比较大的时候导出的html和Draw.io里面画的不一样吗？如果一样的话那就没有必要预览了，所见即所得。

**Comment by wubugg** [comment]
@yaoyi2008  You can cancel grid instead use preview
