### ISSUE TITLE
搜狗输入法第一个字母直接英文

### ISSUE THREAD

**Issue by Jial08** [jgraph/drawio-desktop#483]
不管是win10还是Linux，搜狗输入法的第一个字母都直接英文输入了，从第二个字母才开始按拼音拼写，如下输入哈哈：
[输入异常](https://gitee.com/Jial08/blog-image/raw/master/20210131150702.png)
还请修复该问题，感谢！

**Comment by Zhu-junwei** [comment]
我使用14.1.8没有出现这个问题。

**Comment by Jial08** [comment]
> 我使用14.1.8没有出现这个问题。

14.1.8可以复现这个问题，从左边的通用栏拉一个图标过来，直接搜狗输入汉字，第一个字母就是直接英文输入了，除非将光标点在图标框里。

**Comment by Zhu-junwei** [comment]
> > 我使用14.1.8没有出现这个问题。
> 
> 14.1.8可以复现这个问题，从左边的通用栏拉一个图标过来，直接搜狗输入汉字，第一个字母就是直接英文输入了，除非将光标点在图标框里。

好吧，我使用的是win10自带的输入法

**Comment by Jial08** [comment]
> > > 我使用14.1.8没有出现这个问题。
> > 
> > 
> > 14.1.8可以复现这个问题，从左边的通用栏拉一个图标过来，直接搜狗输入汉字，第一个字母就是直接英文输入了，除非将光标点在图标框里。
> 
> 好吧，我使用的是win10自带的输入法

win10自带的输入法也是一样的，当光标不在图标内的时候直接输入汉字，第一个字母一定是英文直接输入了。

**Comment by Zhu-junwei** [comment]
> > > > 我使用14.1.8没有出现这个问题。
> > > 
> > > 
> > > 14.1.8可以复现这个问题，从左边的通用栏拉一个图标过来，直接搜狗输入汉字，第一个字母就是直接英文输入了，除非将光标点在图标框里。
> > 
> > 
> > 好吧，我使用的是win10自带的输入法
> 
> win10自带的输入法也是一样的，当光标不在图标内的时候直接输入汉字，第一个字母一定是英文直接输入了。

真的耶
![1](https://user-images.githubusercontent.com/29745871/106831979-d3a2fb00-66cb-11eb-9d85-5c8e61265433.gif)

**Comment by Russiarain** [comment]
我感觉这是输入法的bug，我用的Win10自带的微软拼音输入法，在浏览器地址栏，各种文本框，甚至Office软件中打字都会出现第一个字母是英文，第二个开始才中文的情况。

**Comment by Jial08** [comment]
> 我感觉这是输入法的bug，我用的Win10自带的微软拼音输入法，在浏览器地址栏，各种文本框，甚至Office软件中打字都会出现第一个字母是英文，第二个开始才中文的情况。

我电脑win10输入法不存在这个问题

**Comment by Russiarain** [comment]
> > 我感觉这是输入法的bug，我用的Win10自带的微软拼音输入法，在浏览器地址栏，各种文本框，甚至Office软件中打字都会出现第一个字母是英文，第二个开始才中文的情况。
> 
> 我电脑win10输入法不存在这个问题

Win10 bug有个体差异，我刚搜了一下，类似的问题三四年前就有人报告了，一直就没有修复，参见[1](https://www.52pojie.cn/thread-838296-1-1.html) , [2](https://zhidao.baidu.com/question/1179089915992688699.html) , [3](https://tieba.baidu.com/p/5333787852?red_tag=0259119617)

**Comment by donglixp** [comment]
这个应该是Windows的bug

**Comment by linldn** [comment]
这个真的很崩溃啊，打字打不出来

**Comment by grey6966** [comment]
我也是遇到这个问题，好像是最近才有的， 大家看一下有什么共性原因没有？ 大家装过  类似 capslock 等软件吗 ？ 

好久能解决呀，我都想重装系统了

**Comment by Ryan-Wo** [comment]
不只是自带输入法，全部输入法都这样！烦死了，后面的字删除还会调到第一个字母

**Comment by davidjgraph** [comment]
There are two types of editing. 1) input when text editing is live on a shape and 2) input when a shape is selected, not editing is not yet live.

In the first case, that is if you edit by double clicking a shape or pressing enter on a selected shape, the text editor shows and a CJK input (there may be other language) inputs the first character correctly. This is because the text editing is live and we don't have to process anything. The OS IME deals with everything for us.

In the other case, perform text input to a selected cell, we have to capture the event, start the text editing and send the input the the text edit. The problem here is there isn't a way to insert that input back into the OS IME, so we get the input wrong for the first character in certain character sets that require the OS IME to handle them.

We do not have a workaround to the second case. When using CJK, just ensure you always start editing by pressing enter on a selected shape, or double click it.


有两种编辑方式：1）在形状上直接进行实时文本编辑；2）在选择形状时，尚未进入实时编辑状态。

第一种情况是，当你通过双击形状或在选中形状后按下回车键进行编辑时，文本编辑器会显示，且CJK输入法（可能还有其他语言的输入法）可以正确输入第一个字符。这是因为文本编辑处于实时状态，我们无需额外处理，操作系统的输入法编辑器（IME）会处理一切。

第二种情况是，在选中形状后直接输入文本，此时我们需要捕获输入事件，启动文本编辑器，并将输入内容传递给文本编辑器。问题在于，我们无法将该输入重新插入到操作系统的输入法编辑器中，因此在某些需要操作系统IME处理的字符集下，第一个字符的输入会出错。

针对第二种情况，目前我们没有解决方法。使用CJK字符时，请务必通过在选中形状后按下回车键或双击形状来开始编辑。
