### ISSUE TITLE
Screen keeps scrolling to the right by itself

### ISSUE THREAD

**Issue by phredd77** [jgraph/drawio-desktop#544]
After working really hard on an AWS architectural diagram for an assignment, the screen started scrolling right by itself.  (It stops when I put my cursor on one of the categories in the panel on the left where all the shapes (e.g. AWS 18 Compute) are, but resumes when my cursor is in the diagram area.)
 
My mouse is wireless.  I turned it off & back on.  No change.  

Exited Drawio & came back in, hoping the issue would go away.  It didn't.

Turned off the setting in Windows 10 to scroll inactive windows when I hover over them.   Re-booted my PC.  Still doing it.
 
Thanks in advance for any assistance you can provide.

**Comment by davidjgraph** [comment]
What is the draw.io version?

**Comment by phredd77** [comment]
Diagrams.net 14.5.1.

**Comment by davidjgraph** [comment]
Never heard that one, do you have a diagram that reproduces the problem on a different computer?

**Comment by phredd77** [comment]
No, though I sent it to  my wife to see if she could open it.  Apparently
it turns out to be a Windows 10 issue, not a Draw.io issue...  I'll
indicate that on my entry when I can, sometime later today.  (Certain other
apps scroll [down] by themselves.  Have tried all sorts of things, am
probably going to do a system restore next.  Will let you know what I find
out.)

Thanks very much for your quick responses, I really appreciate it!

**Comment by redbeardpete** [comment]
I've seen similar behavior for many many months now. What I'm seeing is after Ctrl+scroll wheel, immediately after releasing Ctrl key, if I scroll again the entire view will shift over. If I'm zooming in, the next scroll wheel movement (either up or down, does not matter) will shift the view way off to the left. If I zoom out, the view shifts way off to the bottom right. If I'm zoomed way in working on some small details, this can be a huge pain because the view shifts miles away, causing me to have to zoom out and re-center.

**Comment by davidjgraph** [comment]
@redbeardpete  The original poster said it was a windows issue. Do you have other apps with this behaviour?

**Comment by redbeardpete** [comment]
Doesn't look like a windows issue because i don't see this behavior
anywhere else. What I noticed is in that moment where this is likely to
happen, just after ctrl+scroll zooming, if I had an item in the diagram
selected before zooming, there's a short time after zooming before the
selected item shows as if it's selected with its highlight and pickup
points again. I think during that short window is when this happens every
time.
