### ISSUE TITLE
The new file does not have no template options

### ISSUE THREAD

**Issue by o6o** [jgraph/drawio-desktop#678]
Ask for big guys, questions like the title.
In the window10 operating system, all drawio versions.
The same is true for reloading after offloading.
What do I do?

Print screens:
New diagram
![图片1](https://user-images.githubusercontent.com/8025096/130206527-62ab87a1-b496-43fb-beb8-c55cc926bb23.png)
No templates are optional
![图片2](https://user-images.githubusercontent.com/8025096/130206539-1319c718-c795-40f5-858c-5c6637ce7405.png)
I expect it to be so
![图片3](https://user-images.githubusercontent.com/8025096/130206543-d1ae1ef0-833c-4151-85ce-0e6af503debe.png)

**Comment by mararad** [comment]
Hi,

"The new file does not have no template options" - not sure I understand you fully. Are you saying that you don't see drawio templates when you click to create a new diagram and also when you open the already created diagrams?

Could you attach print screens please?

Thanks,

**Comment by o6o** [comment]
Yes, that is what you say.

Print screens:

No templates are optional
I expect it to be so













At 2021-08-19 20:23:45, "mararad" ***@***.***> wrote:

Hi,

"The new file does not have no template options" - not sure I understand you fully. Are you saying that you don't see drawio templates when you click to create a new diagram and also when you open the already created diagrams?

Could you attach print screens please?

Thanks,

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mararad** [comment]
Could you please re-attach print screens? I don't see them.

Thanx,

**Comment by o6o** [comment]
Oh, The reply cannot attach the pictures.
But in the email, it is given.
Can you see it in your email?

Thanx.

**Comment by mararad** [comment]
Strange. I can attach PNGs to GitHub issues. My suggestion would be to try with different browser or Incognito mode.

If this doesn't help, please submit all the details with images here: https://groups.google.com/g/drawio so we could take a look

**Comment by o6o** [comment]
Sorry, that is my question.
I have put the picture into the issues. and the problem is solved.
Today I restarted the operating system and found the problem solved, this problem should be caused by no restart after the upgrade.

But is it time to give a hint after the upgrade and it needs to restart.

Thanks for your help.

**Comment by ayrongrenier86** [comment]
Hello guys, i have the same issue with the version 21.2.8, when I open the application and create new diagram the templates are not displayed

![1](https://github.com/jgraph/drawio-desktop/assets/29458646/a8bd5875-9173-43c3-be58-7a01eb4b0c39)

like this:
![2](https://github.com/jgraph/drawio-desktop/assets/29458646/e9f62d54-9067-40df-a57f-21a7710004b8)

when is this how it should be displayed:
![3](https://github.com/jgraph/drawio-desktop/assets/29458646/2493cac3-42c9-4ca5-8780-3af121a3a365)

and the other problem is that the shapes are not displayed too:
![4](https://github.com/jgraph/drawio-desktop/assets/29458646/01bb7f28-a8e0-4851-8ac3-31f7ff939846)

these are displayed like this:
![5](https://github.com/jgraph/drawio-desktop/assets/29458646/e066d6c7-ebcf-4f32-92a0-e51a1c1de822)

and the correct way is this:
![6](https://github.com/jgraph/drawio-desktop/assets/29458646/61733974-baba-4b40-a5a4-c6df147c715e)

I have these problems on Win10 22h2, Win11 22h2 and Linux Mint 21.1 with the desktop app version 21.2.8 and 14.4.3.  Doing some test I found where the problem is. When your device is 100% offline (all network interfaces are disconnected, wifi turned off and no cable connected) and you open the desktop app the templates and shapes don't appear.

And if you connect any network interface even without Internet as long as the operating system recognizes an active network connection, the application works correctly.

I think this will help you to fix the problem. And by the way, great application guys.
