### ISSUE TITLE
%date{isoDate}% %date{isoTime}% combination fails 14.9.6 .. 20.7.4

### ISSUE THREAD

**Issue by ll3141** [jgraph/drawio-desktop#697]
* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio-desktop/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
using both placeholders %date{isoDate}% %date{isoTime}% in one texts displays garbage

**To Reproduce**
have a look at the screenshot and the attached file

**Expected behavior**
the text containing both placeholders should display correctly

**Screenshots**
left boxes are identical copies of the right ones, only with "placeholder" checkbox checked
![image](https://user-images.githubusercontent.com/87464784/132510736-61a4f28d-30f4-4335-ac0c-879de8cf154a.png)
[isoDate_isoTime_Error.zip](https://github.com/jgraph/drawio-desktop/files/7128886/isoDate_isoTime_Error.zip)

**draw.io version (In the Help->About menu of the draw.io editor):**
- draw.io version 14.9.6

**Desktop (please complete the following information):**
 - OS: windows 10 pro (10.0.19042)

**Comment by ll3141** [comment]
problem persists with 15.1.3

**Comment by bt-tech-dd** [comment]
This bug is still present in 15.3.8. As a side note if I type in the ISO formats manually as such, %date{yyyy-mm-dd}% %date{HH:MM:ss}%. The bug also occurs with the output looking like "2021-09-30}% %30aae{11:49:27" instead of the expected "2021-09-30 11:49:27". So this bug is not limited to strictly those two date formats in the OP.

**Comment by ll3141** [comment]
still persists with 20.3.0

**Comment by ll3141** [comment]
persists with 20.7.4

**Comment by bt-tech-dd** [comment]
The issue with having multiple `%date{xxx}%` format styles in a single element is still present in version 22.1.18. One thing I noticed while testing in this version is that if you, for example, put `%date{isoDate}% %date{longDate}%` and you move the element around, the errored text will change. However this does not correlate to the element's position because if you move it back to the same spot, the text is different. Not sure if this is significant information or not but I'd thought I would mention it due to its strangeness.
