### ISSUE TITLE
Add option to save diagram without compression for version control

### ISSUE THREAD

**Issue by olfek** [jgraph/drawio-desktop#79]
Hello,

Please add an option to save the diagram without compression so that it is suitable to be version controlled.

Thank you.

PS. I'm referring to the compression explained here: https://about.draw.io/extracting-the-xml-from-mxfiles/

**Comment by rmg** [comment]
I spent some time poking at this and tinkering for a while and it turns out that even once you extract and convert the base64 blob and replace it with regular xml, draw.io can't even open it. I haven't verified yet, but it seems like the use of encoding and compression are currently non-optional.

**Comment by alderg** [comment]
Experimental support for this will be added in the next release. To enable it, add compressed="false" attribute to mxfile node.

**Comment by r146023** [comment]
Could there be an option to have it just save the draw.io file as the uncompressed/unencoded xml by default?
I LOVE draw.io, I use python to modify my diagrams often, when I save the drawing from the vscode plug in, it saves it in a usable format by default, but if I use the desktop software, it compresses it so that I have to manually save it specifically as xml, if I want my scripts to be able to read them.
Would it be feasible to have a toggle for how it saves the file by default?
OR! Is there a python library/resource I could use to detect the compression and decompress it?

**Comment by davidjgraph** [comment]
We'll reopen https://github.com/jgraph/drawio-desktop/issues/200 issue for an option in the UI

**Comment by davidjgraph** [comment]
Literally nobody seems to want compression, so we'll default to uncompressed in the next release.

**Comment by olfek** [comment]
yay
